config/routes.rb
Rails.application.routes.draw do
  root to: 'exercises#index'

  resources :exercises do
    post :start_container, on: :member
    post :update_container, on: :member
    resources :iterations
  end

  post '/exercises/:exercise_id/iterations/:token/run_tests', to: 'iterations#run_tests', as: :run_tests
  post '/exercises/:exercise_id/iterations/:token/start_container', to: 'iterations#start_container', as: :start_container
  post '/exercises/:exercise_id/iterations/:token/stop_container', to: 'iterations#stop_container', as: :stop_container
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :iterations, dependent: :destroy
  has_one_attached :test_file

  def tests
    test_file.blob.download
  end

  def test_file_on_disk
    ActiveStorage::Blob.service.send(:path_for, test_file.key)
  end

  def test_file_name
    "#{name.parameterize(separator: '_')}_test.rb"
  end

  def exercise_file_name
    "#{name.parameterize(separator: '_')}.rb"
  end
end

app/models/iteration.rb
class Iteration < ApplicationRecord
  belongs_to :exercise, counter_cache: true
  has_one_attached :file

  def code
    file.blob.download if file.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy, :start_container, :update_container]

  def index
    @exercises = Exercise.all
  end

  def show
  end

  def new
    @exercise = Exercise.new
    @tests = <<~TESTS
      require 'minitest/autorun'
      require 'minitest/reporters'
      require 'minitest/reporters/json_reporter'
      Minitest::Reporters.use! Minitest::Reporters::JsonReporter.new

    TESTS
  end

  def edit
    @tests = @exercise.tests
  end

  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      @exercise.test_file.attach(io: StringIO.new(params[:exercise][:tests]), filename: "#{@exercise.name}_test.rb")
      redirect_to @exercise, notice: 'Exercise was successfully created.'
    else
      render :new
    end
  end

  def update
    if @exercise.update(exercise_params)
      @exercise.test_file.attach(io: StringIO.new(params[:exercise][:tests]), filename: "#{@exercise.name}_test.rb")
      redirect_to @exercise, notice: 'Exercise was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    redirect_to exercises_url, notice: 'Exercise was successfully destroyed.'
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:name, :icon, :description, :test_file)
    end
end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  before_action :set_exercise
  before_action :set_iteration, only: [:show, :edit, :update, :destroy]
  before_action :find_container, only: [:run_tests, :stop_container]

  def index
    @iterations = @exercise.iterations.all
  end

  def show
  end

  def new
    @iteration = @exercise.iterations.build
    @token = SecureRandom.hex(5)
  end

  def edit
  end

  def create
    @iteration = @exercise.iterations.build(iteration_params[:file])
    @iteration.number = @exercise.iterations_count + 1

    if @iteration.save
      @iteration.file.attach(io: StringIO.new(params[:iteration][:code]), filename: "#{@exercise.name}.rb")
      redirect_to [@exercise, @iteration], notice: 'Iteration was successfully created.'
    else
      render :new
    end
  end

  def update
    if @iteration.update(iteration_params)
      redirect_to @iteration, notice: 'Iteration was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @iteration.destroy
    redirect_to exercise_iterations_url, notice: 'Iteration was successfully destroyed.'
  end

  def start_container
    if Containers::Start.new(exercise: @exercise, token: params[:token]).call
      head :ok
    else
      head :internal_server_error
    end
  end

  def run_tests
    if @output = Containers::Run.new(container: @container, exercise: @exercise, code: params[:code]).call
      if @output.blank?
        head :internal_server_error
        return
      end

      @sorted_results = ResultPresenter.new(@output, @exercise.tests).sort
      Containers::KeepAlive.new(token: params[:token]).call

      respond_to do |format|
        format.js
      end
    else
      head :internal_server_error
    end
  end

  def stop_container
    Containers::Stop.new(container: @container).call
  end

  private

    def find_container
      @container = Docker::Container.get($redis.hget(params[:token], :container_id))
    end

    def set_exercise
      @exercise = Exercise.find(params[:exercise_id])
    end

    def set_iteration
      @iteration = @exercise.iterations.find(params[:id])
    end

    def iteration_params
      params.require(:iteration).permit(:file, :token, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <% if exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :tests %>
    <%= form.text_area :tests, value: @tests, id: "editor" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exercises/attempt.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exercise.description %>
</p>

<p>
  <strong>Editor:</strong>
  <%= text_area_tag "editor", nil, class: "editor" %>
</p>

<p>
  <strong>Tests:</strong>
  <%= text_area_tag "exercise_tests", @exercise.tests, class: "editor" %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form', exercise: @exercise %>

<%= link_to 'Back', @exercise %> |
<%= link_to 'Back to exercises', exercises_path %>

app/views/exercises/index.html.erb
<div class="exercises-index">
  <p id="notice"><%= notice %></p>

  <h1>
    <span>Exercises</span>
    <%= link_to new_exercise_path, class: "btn btn-success float-right mt-2" do %>
      <i class="fas fa-plus"></i> Create Exercise
    <% end %>
  </h1>
  <hr/>

  <% @exercises.each do |exercise| %>
    <div class="card my-3">
      <div class="card-header">
        <%= exercise.name %>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= exercise.description.truncate_words(30, omission: '...')%>
        </p>
        <div class="btn-group">
          <%= link_to new_exercise_iteration_path(exercise), class: "btn btn-success btn-sm px-3" do %>
            <i class="fas fa-keyboard"></i> Open
          <% end %>

          <%= link_to exercise_iterations_path(exercise), class: "btn btn-primary btn-sm px-3" do %>
            <i class="fas fa-history"></i> History
          <% end %>

          <%= link_to edit_exercise_path(exercise), class: "btn btn-warning btn-sm px-3" do %>
            <i class="fas fa-edit"></i> Edit
          <% end %>

          <%= link_to exercise, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm px-3" do %>
            <i class="fas fa-trash-alt"></i> Delete
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form', exercise: @exercise %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exercise.description %>
</p>

<p>
  <strong>Tests:</strong>
  <%= text_area_tag "exercise_tests", @exercise.tests, id: "tests" %>
</p>

<%= link_to 'Attempt', new_exercise_iteration_path(@exercise) %> |
<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/iterations/_form.html.erb
<%= form_with(model: [exercise, iteration]) do |form| %>
  <% if iteration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

      <ul>
        <% iteration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field editor-container">
    <%= form.label :code %>
    <%= form.text_area :code, class: "editor" %>
  </div>

  <div class="editor-container">
    <strong>Tests:</strong>
    <%= text_area_tag "exercise_tests", exercise.tests, class: "read-only-editor" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/iterations/_test_results.html.erb
<%# results = JSON.parse(CGI.unescape(@output), symbolize_names: true) %>
<% @sorted_results.each do |result| %>
  <% color = result[:passed] ? "success" : "danger" %>
  <li class="test-result list-group-item list-group-item-<%= color %>" id="<%= result[:name] %>" style="width: 100%;">
    <strong><%= result[:name] %></strong>
  </li>
<% end %>

app/views/iterations/create.js.erb
alert('hi')

app/views/iterations/edit.html.erb
<h1>Editing Iteration</h1>

<%= render 'form', iteration: @iteration, exercise: @exercise %>

<%= link_to 'Show', [@exercise, @iteration] %> |
<%= link_to 'Back', exercise_iterations_path(@exercise) %>

app/views/iterations/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @exercise.name %></h1>

<table>
  <thead>
    <tr>
      <th>Attempt number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iterations.each do |iteration| %>
      <tr>
        <td><%= iteration.number %></td>
        <td><%= link_to 'Show', exercise_iteration_path(iteration.exercise, iteration) %></td>
        <td><%= link_to 'Edit', edit_exercise_iteration_path(iteration.exercise, iteration) %></td>
        <td><%= link_to 'Destroy', exercise_iteration_path(iteration.exercise, iteration), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New iteration', new_exercise_iteration_path(@exercise) %>
|
<%= link_to 'Back to exercises', exercises_path %>

app/views/iterations/new.html.erb
<div class="iterations-new">
  <div class="row">
    <div class="col-3 p-3">
      <h1 class="exercise-title">
        <%= image_tag(@exercise.icon + ".png", size: 35, style: 'display: inline; margin-bottom: 0.2em') unless @exercise.icon.empty? %>
        <%= @exercise.name %>
      </h1>
      <div class="exercise-description">
        <%= simple_format(@exercise.description) %>
      </div>
    </div>
    <div class="col-9">
    <%= form_with(model: [@exercise, @iteration], remote: true, id: "exercise-form") do |form| %>
      <div class="row">
        <div class="col p-0">
          <% if @iteration.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

              <ul>
                <% @iteration.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>

      <%= form.hidden_field :exercise_id, value: @exercise.id %>
      <%= form.hidden_field :token, value: @token %>

      <div class="row">
        <div class="col-6 p-0">
          <%= form.text_area :code, id: "editor" %>
        </div>

        <div class="col-6 p-0">
          <%= text_area_tag "exercise_tests", @exercise.tests, id: "tests" %>
        </div>

      </div>
    <% end %>

    <div class="row">
      <div class="col-9 px-0 pt-2">
        <div class="alert alert-primary mb-2" role="alert">
          Use <code>Ctrl + Enter</code> to run tests.
        </div>
      </div>
      <div class="col-3 p-2">
        <div class="btn-group" style="width: 100%;">
          <input id="run_tests" type="button" value="Run" class="btn btn-lg btn-primary" disabled/>
          <button type="submit" form="exercise-form" class="btn btn-lg btn-success">Save</button>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col p-0">
        <%#= text_area_tag "terminal", nil, id: "terminal" %>
        <div id="test_results"></div>
      </div>
    </div>
    <%#= link_to 'Back', exercises_path %>
  </div>
</div>


<%= javascript_pack_tag "exercises" %>

app/views/iterations/run_tests.js.erb
// terminal.doc.setValue('<%= json_escape(@output) %>');
$('#test_results').html("<%= j(render "iterations/test_results") %>")

app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Attempt number:</strong>
  <%= @iteration.number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exercise.description %>
</p>

<p class="editor-container">
  <strong>Code:</strong>
  <%= text_area_tag "iteration_code", @iteration.code, id: "editor" %>
</p>

<p class="editor-container">
  <strong>Tests:</strong>
  <%= text_area_tag "exercise_tests", @exercise.tests, id: "tests" %>
</p>

<%= link_to 'Edit', edit_exercise_iteration_path(@iteration) %> |
<%= link_to "Back to #{@exercise.name}", exercise_iterations_path(@exercise) %>
|
<%= link_to 'Back to exercises', exercises_path %>

app/views/iterations/update_terminal.js.erb
alert('hi');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyperbolic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>